const demo = {
  student:{name:'Ali Yıldız', grade:'9. Sınıf', goal:'Lefkoşa Fen Lisesi', tests:128, correct:892, wrong:356, empty:64, time:'18sa 45dk', net:'66.00'},
  subjects:[['Türkçe',80],['Matematik',48],['Fen Bilimleri',72],['Sosyal Bilgiler',65],['İngilizce',75]],
  tasks:[['Matematik','20 soru çöz',70],['Türkçe','Paragraf testi',45],['Fen Bilimleri','15 soru çöz',80],['İngilizce','Kelime çalış',35]],
  tests:[['2026 Fen Lisesi Deneme - 1','Tüm Dersler',72,18,'66.00','18.05.2026'],['Matematik - Oran Orantı Testi','Matematik',8,2,'7.25','17.05.2026'],['Türkçe - Paragraf Testi','Türkçe',9,1,'8.75','17.05.2026'],['Fen Bilimleri - Canlılar Testi','Fen',7,3,'6.25','16.05.2026']],
  weak:[['Matematik - Oran Orantı',35],['Matematik - Cebirsel İfadeler',42],['Fen Bilimleri - Kimyasal Tepkimeler',45],['Türkçe - Paragraf',50],['Sosyal Bilgiler - Harita Bilgisi',65]],
  questions:[
    {lesson:'Matematik', q:'Bir sayının %25’i 18 ise bu sayı kaçtır?', o:['36','54','72','90'], a:2, exp:'18 sayısı dörtte biri ise 18 x 4 = 72.'},
    {lesson:'Türkçe', q:'“Kitap okumayı çok severim.” cümlesinde yüklem hangisidir?', o:['Kitap','Okumayı','Çok','Severim'], a:3, exp:'Cümlede işi bildiren kelime “severim”dir.'},
    {lesson:'Fen', q:'Fotosentez için aşağıdakilerden hangisi gereklidir?', o:['Işık','Tuz','Kum','Ses'], a:0, exp:'Bitkiler fotosentez için ışığa ihtiyaç duyar.'}
  ]
};
let state={role:'student', screen:'home', activeQ:0, selected:null};
const app=document.getElementById('app');
function login(){app.innerHTML=`<div class="login"><section class="hero"><div><div class="brand"><span class="star">★</span><div>STAR ACADEMY<br><small>CYPRUS</small></div></div><h1>KKTC Fen Lisesi & BEAL Hazırlık Platformu</h1><p>Çıkmış sorular, mini konu anlatımları, hızlı testler, deneme sınavları, veli takibi ve admin yönetimi tek sistemde.</p><div class="mock-previews"><img src="assets/student-preview.png"><img src="assets/parent-preview.png"></div></div><p>© 2026 Star Academy Cyprus</p></section><section class="login-panel"><div class="login-card"><h2>Giriş Yap</h2><p class="muted">Demo sürüm için rol seçip giriş yapabilirsin.</p><div class="role-grid">${roleBtn('student','Öğrenci')} ${roleBtn('parent','Veli')} ${roleBtn('admin','Admin')}</div><div class="field"><label>Kullanıcı adı</label><input id="u" value="${state.role==='student'?'ogrenci':state.role==='parent'?'veli':'admin'}"></div><div class="field"><label>Şifre</label><input id="p" type="password" value="1234"></div><button class="btn" onclick="enter()">Sisteme Gir</button><div class="hint"><b>Demo:</b> öğrenci / veli / admin kullanıcı adlarından biri ve şifre <b>1234</b>.</div></div></section></div>`}
function roleBtn(r,t){return `<button class="role ${state.role===r?'active':''}" onclick="state.role='${r}';login()">${t}</button>`}
function enter(){state.screen='home'; render()}
function navItems(){let common=[['home','Ana Sayfa','⌂'],['lessons','Konu Anlatımları','📘'],['quiz','Mini Testler','⚡'],['exam','Deneme Sınavları','📝'],['past','Çıkmış Sorular','📂'],['stats','İstatistikler','📊']]; if(state.role==='parent') return [['home','Veli Özeti','👨‍👩‍👦'],['child','Çocuğumun Durumu','🎓'],['exam','Deneme Sonuçları','📝'],['stats','Ders Başarıları','📊'],['messages','Öğretmen Notları','💬']]; if(state.role==='admin') return [['home','Admin Panel','⚙️'],['questions','Soru Yönetimi','➕'],['lessons','Konu Yönetimi','📘'],['students','Öğrenciler','👥'],['reports','Raporlar','📊']]; return common.concat([['wrong','Yanlışlarım','❌'],['notes','Notlarım','⭐']]);}
function shell(content,title){app.innerHTML=`<div class="layout"><aside class="side"><div class="brand"><span class="star">★</span><div>STAR ACADEMY<br><small>CYPRUS</small></div></div>${navItems().map(n=>`<button class="navbtn ${state.screen===n[0]?'active':''}" onclick="state.screen='${n[0]}';render()"><span>${n[2]}</span>${n[1]}</button>`).join('')}<div class="userbox"><b>${state.role==='parent'?'Ayşe Yıldız':state.role==='admin'?'Hüseyin Yıldız':demo.student.name}</b><br><span class="muted">${state.role==='parent'?'Veli Portalı':state.role==='admin'?'Sistem Yöneticisi':demo.student.grade}</span><br><br><button class="btn ghost" onclick="login()">Çıkış Yap</button></div></aside><main class="main"><div class="top"><div><h1>${title}</h1><p class="muted">Fen Lisesi ve BEAL hazırlık demo sistemi</p></div><input class="search" placeholder="Ara: konu, test, öğrenci..."></div>${content}<div class="footer">STAR ACADEMY CYPRUS - GitHub Pages demo sürümü</div></main></div>`}
function metric(icon,t,v,s){return `<div class="card metric"><div><h3>${t}</h3><b>${v}</b><p class="muted">${s||''}</p></div><div class="icon">${icon}</div></div>`}
function studentHome(){return `${cards()}<div class="grid"><div class="card banner"><h2>Fen Lisesi & BEAL hayaline ulaşmanın en doğru yolu!</h2><p>Planlı çalış, hızlı tekrar yap ve deneme sonuçlarını takip et.</p><button class="btn gold" onclick="state.screen='quiz';render()">Hemen Çalışmaya Başla →</button></div><div class="card tasks"><h2>Günlük Görevlerin</h2>${demo.tasks.map(x=>`<div class="row"><b>${x[0]}</b><span>${x[1]}</span><div class="bar"><span style="width:${x[2]}%"></span></div></div>`).join('')}</div></div>${subjects()}${recentTests()}<div class="section card"><h2>Hızlı İşlemler</h2><div class="actions"><button class="action" onclick="state.screen='quiz';render()">⚡<br>Mini Test</button><button class="action" onclick="state.screen='exam';render()">📝<br>Deneme Sınavı</button><button class="action" onclick="state.screen='wrong';render()">❌<br>Yanlışlarım</button><button class="action" onclick="state.screen='past';render()">📂<br>Çıkmış Sorular</button></div></div>`}
function cards(){return `<div class="cards">${metric('📚','Toplam Test',demo.student.tests,'Bu ay')}${metric('✅','Doğru',demo.student.correct,'Başarı sorusu')}${metric('❌','Yanlış',demo.student.wrong,'Tekrar edilecek')}${metric('⏱','Çalışma Süresi',demo.student.time,'Toplam')}</div>`}
function subjects(){return `<div class="section card"><h2>Derslere Göre Başarı Durumun</h2><div class="subject-grid">${demo.subjects.map(s=>`<div class="subject"><div class="circle">%${s[1]}</div><b>${s[0]}</b><p class="muted">${s[1]>70?'Çok iyi':s[1]>55?'İyi':'Geliştirilmeli'}</p></div>`).join('')}</div></div>`}
function recentTests(){return `<div class="section card"><h2>Son Çözdüğün Testler</h2><table class="table"><tr><th>Test</th><th>Ders</th><th>Doğru</th><th>Yanlış</th><th>Net</th><th>Tarih</th></tr>${demo.tests.map(t=>`<tr>${t.map(v=>`<td>${v}</td>`).join('')}</tr>`).join('')}</table></div>`}
function parentHome(){return `<div class="parent-head"><div class="card student-profile"><div class="avatar">👦</div><div><h2>${demo.student.name} <span class="pill success">Aktif Öğrenci</span></h2><p>${demo.student.grade} • ${demo.student.goal}</p><span class="pill">Profil Bilgileri</span></div></div>${metric('📄','Çözdüğü Test',demo.student.tests,'Bu ay')}${metric('✅','Doğru',demo.student.correct,'Bu ay')}${metric('❌','Yanlış',demo.student.wrong,'Bu ay')}${metric('⏱','Süre',demo.student.time,'Bu ay')}</div><div class="grid"><div class="card"><h2>Genel Başarı Durumu</h2><div class="circle" style="width:150px;height:150px;font-size:32px">%68</div><p class="success">Geçen aya göre %8 artış gösterdi.</p></div><div class="card weak"><h2>En Zayıf Olduğu Konular</h2>${demo.weak.map(w=>`<li><b>${w[0]}</b><div class="bar"><span style="width:${w[1]}%;background:var(--orange)"></span></div><span class="muted">%${w[1]}</span></li>`).join('')}</div></div>${subjects()}${recentTests()}<div class="grid"><div class="card"><h2>Haftalık Çalışma Özeti</h2><div class="cards">${metric('📅','Giriş','6','gün')}${metric('📗','Test','42','adet')}</div></div><div class="card"><h2>Öğretmen Notu</h2><p>Ali bu hafta özellikle matematikte ilerleme kaydetti. Oran orantı konusuna daha fazla çalışması faydalı olacaktır.</p></div></div>`}
function adminHome(){return `<div class="cards">${metric('👥','Öğrenci','248','Kayıtlı')}${metric('👨‍👩‍👦','Veli','196','Bağlı hesap')}${metric('❓','Soru','1.420','Havuz')}${metric('📝','Deneme','28','Aktif')}</div><div class="grid"><div class="card"><h2>Yeni Soru Ekle</h2><div class="admin-form"><input placeholder="Ders"><input placeholder="Konu"><input placeholder="Doğru cevap"><input placeholder="Zorluk"><textarea placeholder="Soru metni / açıklama"></textarea><button class="btn">Soruyu Kaydet</button></div></div><div class="card"><h2>Sistem Özeti</h2><p>Bu demo sürümde admin, öğrenci ve veli panelleri hazırlandı. Gerçek kullanımda Firebase ile giriş, soru havuzu ve sonuç kayıtları bağlanabilir.</p><button class="btn gold">PDF Soru Havuzu Aktar</button></div></div>${recentTests()}`}
function lessonPage(){return `<div class="cards">${['Matematik','Türkçe','Fen Bilimleri','Sosyal Bilgiler'].map(x=>metric('📘',x,'Mini Konular','Özet + test')).join('')}</div><div class="section card"><h2>Mini Konu Anlatımı Örneği</h2><h3>Matematik - Oran Orantı</h3><p>İki çokluğun birbirine bölünerek karşılaştırılmasına oran denir. Oranların eşitliğine orantı denir. Sınavlarda genellikle yaş, hız, karışım ve yüzde problemleriyle birlikte gelir.</p><span class="pill">5 dakikalık hızlı tekrar</span></div>`}
function quizPage(){let q=demo.questions[state.activeQ];return `<div class="card"><span class="pill">${q.lesson}</span><div class="question">${q.q}</div>${q.o.map((o,i)=>`<button class="option ${state.selected===i?(i===q.a?'correct':'wrong'):''}" onclick="state.selected=${i};render()">${String.fromCharCode(65+i)}) ${o}</button>`).join('')}${state.selected!==null?`<p><b>Açıklama:</b> ${q.exp}</p><button class="btn" onclick="state.activeQ=(state.activeQ+1)%demo.questions.length;state.selected=null;render()">Sonraki Soru</button>`:''}</div>`}
function examPage(){return `<div class="card banner"><h2>2026 Fen Lisesi Deneme Sınavı</h2><p>Süreli deneme ekranı, optik mantığı ve sonuç raporu için hazır taslak.</p><button class="btn gold">Denemeyi Başlat</button></div>${recentTests()}`}
function generic(title){return `<div class="card"><h2>${title}</h2><p>Bu bölüm demo sürümde hazırlandı. İkinci aşamada gerçek veritabanı, PDF aktarımı ve kullanıcı bazlı kayıt sistemi eklenecek.</p></div>${subjects()}`}
function render(){if(state.role==='student'){let map={home:studentHome,lessons:lessonPage,quiz:quizPage,exam:examPage,past:()=>generic('Çıkmış Sorular'),stats:()=>generic('İstatistikler'),wrong:()=>generic('Yanlışlarım'),notes:()=>generic('Notlarım')};shell((map[state.screen]||studentHome)(), state.screen==='home'?'Hoş geldin, Ali!':'Öğrenci Paneli')} else if(state.role==='parent'){let map={home:parentHome,child:parentHome,exam:examPage,stats:()=>generic('Derslere Göre Başarı'),messages:()=>generic('Öğretmen Mesajları')};shell((map[state.screen]||parentHome)(), 'Hoş geldiniz, Ayşe Yıldız')} else {let map={home:adminHome,questions:adminHome,lessons:lessonPage,students:()=>generic('Öğrenci Yönetimi'),reports:()=>generic('Raporlar')};shell((map[state.screen]||adminHome)(), 'Admin Panel')}}
login();
if('serviceWorker' in navigator){navigator.serviceWorker.register('./service-worker.js').catch(()=>{})}
